require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    'arduino',
    'astro',
    'bash',
    'c',
    'c_sharp',
    'cmake',
    'comment',
    'cpp',
    'css',
    'diff',
    'dockerfile',
    'gdscript',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'glsl',
    'go',
    'graphql',
    'hjson',
    'html',
    'http',
    'javascript',
    'jsdoc',
    'json5',
    'kotlin',
    'latex',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'prisma',
    'python',
    'regex',
    'robot',
    'rust',
    'scss',
    'svelte',
    'terraform',
    'todotxt',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'vue',
    'wgsl',
    'wgsl_bevy',
    'yaml',
    'zig',
  },
  sync_install = false,
  highlight = {
    enable = true,
    disable = { '' },
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
    disable = { 'yaml' }
  },
  context_commentstring = {
    enable = true,
    enable_autocmd = true
  },
}

