return {
  leader = ' ',
  lsp = {
    declaration = 'gD',
    definition = 'gd',
    definition_hover = 'K',
    implementation = 'gi',
    signature = 'gh',
    references = 'gr',
    diagnostic = 'gl',
    diagnostic_prev = '[d',
    diagnostic_next = ']d',
    diagnostic_setloclist = 'gq',
    code_action = 'ga',
  },
  code = {
    paste = 'p',
    indent_back = '<',
    indent_forward = '>',
    move_word_back = '<leader>wb',
    move_word_forward = '<leader>wf',
    move_line_up = '<M-k>',
    move_line_down = '<M-j>',
  },
  cmp = {
    select_prev = '<C-k>',
    select_next = '<C-j>',
    scroll_prev = '<C-b>',
    scroll_next = '<C-f>',
    complete = '<C-Space>',
    disable = '<C-y>',
    abort = '<C-e>',
    select = '<CR>',
    cycle_next = '<tab>',
    cycle_prev = '<S-tab>',
  },
  buffers = {
    list = '<leader>l',
    prev = '<S-h>',
    next = '<S-l>',
    last_prev = '<tab>',
    last_next = '<S-tab>',
    close = '<leader>c',
    save = '<leader>w',
    new = '<leader>m',
    rename = '<leader>r',
    history = '<leader>t',
    move_left = '<C-h>',
    move_right = '<C-l>',
    move_up = '<C-k>',
    move_down = '<C-j>',
    resize_left = '<A-Left>',
    resize_right = '<A-right>',
    resize_up = '<A-Up>',
    resize_down = '<A-Down>',
    split_vertical = '<leader>|',
    split_horizontal = '<leader>-'
  },
  ui = {
    file_explorer = '<leader>e',
    colorscheme = '<leader>fc',
  },
  search = {
    find_files = 'ff',
    find_word = 'fw',
    find_history = 'fh',
    unselect = '<leader>h',
    next_select = 'n',
    prev_select = 'N',
  },
  git = {
    status = 'gs',
  },
}

